[package]
name = "leonard"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
strip-ansi-escapes = "0.2"
time = { version = "0.3", features = ["local-offset", "formatting"] }
